# Dictionary containing diseases as keys and corresponding medicines as values
medicine_database = {
    "cold": ["paracetamol", "ibuprofen", "decongestants"],
    "fever": ["paracetamol", "ibuprofen", "aspirin"],
    "headache": ["paracetamol", "ibuprofen"],
    "flu": ["antiviral medication", "decongestants", "pain relievers"],
    "allergies": ["antihistamines", "decongestants"],
    "influenza": ["oseltamivir", "zanamivir", "peramivir"],
    "hypertension": ["lisinopril", "amlodipine", "metoprolol"],
    "diabetes": ["insulin", "metformin", "glipizide"],
    "asthma": ["albuterol", "fluticasone", "montelukast"],
    "migraine": ["sumatriptan", "propranolol", "topiramate"],
    "arthritis": ["ibuprofen", "naproxen", "celecoxib"],
    "depression": ["sertraline", "escitalopram", "venlafaxine"],
    "anxiety": ["alprazolam", "clonazepam", "buspirone"],
    "hypothyroidism": ["levothyroxine", "liothyronine"],
    "hyperthyroidism": ["methimazole", "propylthiouracil"],
    "gastroesophageal reflux disease (GERD)": ["omeprazole", "ranitidine", "famotidine"],
    "allergies": ["loratadine", "cetirizine", "diphenhydramine"],
    "osteoporosis": ["alendronate", "risedronate", "ibandronate"],
    "chronic obstructive pulmonary disease (COPD)": ["tiotropium", "salmeterol", "fluticasone"],
    "acid peptic disorders": ["esomeprazole", "pantoprazole", "rabeprazole"],
    "epilepsy": ["phenytoin", "valproate", "carbamazepine"],
    "heart failure": ["furosemide", "spironolactone", "digoxin"],
    "malaria": ["chloroquine", "artemether", "atovaquone-proguanil"],
    "urinary tract infection (UTI)": ["nitrofurantoin", "ciprofloxacin", "trimethoprim-sulfamethoxazole"],
    "hypertensive emergencies": ["nitroglycerin", "hydralazine", "nitroprusside"],
    "acute coronary syndrome": ["aspirin", "clopidogrel", "heparin"],
    "rheumatoid arthritis": ["methotrexate", "adalimumab", "etanercept"],
    "cirrhosis": ["spironolactone", "propranolol", "lactulose"],
    "pneumonia": ["amoxicillin", "azithromycin", "levofloxacin"],
    "menopause": ["estradiol", "medroxyprogesterone", "clonidine"],
    "gout": ["allopurinol", "colchicine", "indomethacin"],
    "parkinson's disease": ["levodopa-carbidopa", "pramipexole", "rasagiline"],
    "osteoarthritis": ["acetaminophen", "diclofenac", "naproxen"],
    "schizophrenia": ["risperidone", "olanzapine", "quetiapine"],
    "bipolar disorder": ["lithium", "valproate", "lamotrigine"],
    "stroke": ["aspirin", "clopidogrel", "tPA (alteplase)"],
    "anemia": ["iron supplements", "erythropoietin", "vitamin B12"],
    "chronic kidney disease": ["lisinopril", "losartan", "furosemide"],
    "migraine": ["sumatriptan", "propranolol", "topiramate"],
    "obesity": ["orlistat", "phentermine", "liraglutide"],
    "inflammatory bowel disease (IBD)": ["mesalamine", "prednisone", "azathioprine"],
    "chronic kidney disease": ["lisinopril", "losartan", "furosemide"],
    "vitamin deficiency": ["vitamin D", "vitamin B12", "folic acid"],
    "pulmonary embolism": ["enoxaparin", "warfarin", "rivaroxaban"],
    "hyperlipidemia": ["atorvastatin", "simvastatin", "ezetimibe"],
    "multiple sclerosis": ["interferon beta-1a", "glatiramer acetate", "dimethyl fumarate"],
    "chronic pancreatitis": ["pancrelipase", "omeprazole", "creon"],
    "hypoglycemia": ["glucose tablets", "glucagon", "diazoxide"],
    "coronary artery disease (CAD)": ["aspirin", "atorvastatin", "metoprolol"],
    "hemorrhoids": ["hydrocortisone", "witch hazel", "phenylephrine"],
    "acne": ["benzoyl peroxide", "salicylic acid", "adapalene"],
    "diverticulitis": ["metronidazole", "ciprofloxacin", "amoxicillin-clavulanate"],
    "gastroenteritis": ["oral rehydration solution", "ondansetron", "loperamide"],
    "deep vein thrombosis (DVT)": ["enoxaparin", "rivaroxaban", "warfarin"],
    "chronic sinusitis": ["amoxicillin-clavulanate", "doxycycline", "fluticasone nasal spray"],
    "tuberculosis": ["isoniazid", "rifampin", "ethambutol"],
    "conjunctivitis": ["artificial tears", "topical antibiotics", "antihistamine eye drops"],
    "benign prostatic hyperplasia (BPH)": ["tamsulosin", "finasteride", "alfuzosin"],
    "glaucoma": ["timolol", "brimonidine", "latanoprost"],
    "pulmonary hypertension": ["sildenafil", "bosentan", "epoprostenol"],
    "gastrointestinal bleeding": ["proton pump inhibitors", "octreotide", "transfusion"],
    "liver abscess": ["metronidazole", "ceftriaxone", "ampicillin-sulbactam"],
    "tonsillitis": ["penicillin", "amoxicillin", "clindamycin"],
    "seborrheic dermatitis": ["ketoconazole shampoo", "ciclopirox cream", "coal tar shampoo"],
    "pancreatic cancer": ["gemcitabine", "nab-paclitaxel", "fluorouracil"],
    "irritable bowel syndrome (IBS)": ["linaclotide", "rifaximin", "dicyclomine"],
    "atrial fibrillation": ["warfarin", "dabigatran", "rivaroxaban"],
    "congestive heart failure (CHF)": ["furosemide", "spironolactone", "digoxin"],
    "endometriosis": ["oral contraceptives", "gonadotropin-releasing hormone agonists", "danazol"],
    "systemic lupus erythematosus (SLE)": ["hydroxychloroquine", "prednisone", "mycophenolate mofetil"],
    "chronic lymphocytic leukemia (CLL)": ["rituximab", "ibrutinib", "venetoclax"],
    "prostate cancer": ["leuprolide", "bicalutamide", "docetaxel"],
    "ovarian cancer": ["paclitaxel", "carboplatin", "bevacizumab"],
    "melanoma": ["ipilimumab", "nivolumab", "pembrolizumab"],
    "multiple myeloma": ["bortezomib", "lenalidomide", "dexamethasone"],
    "chronic myeloid leukemia (CML)": ["imatinib", "dasatinib", "nilotinib"],
    "breast cancer": ["tamoxifen", "letrozole", "trastuzumab"],
    "colon cancer": ["fluorouracil", "oxaliplatin", "irinotecan"],
    "lung cancer": ["cisplatin", "pemetrexed", "docetaxel"],
    "glioblastoma": ["temozolomide", "bevacizumab", "carmustine"],
    "pancreatic cancer": ["gemcitabine", "nab-paclitaxel", "fluorouracil"],
    "bladder cancer": ["cisplatin", "gemcitabine", "bacillus Calmette-Guerin (BCG)"],
    "testicular cancer": ["cisplatin", "etoposide", "bleomycin"],
    "renal cell carcinoma": ["sunitinib", "pazopanib", "nivolumab"],
    "hepatocellular carcinoma": ["sorafenib", "lenvatinib", "regorafenib"],
    "thyroid cancer": ["levothyroxine", "radioactive iodine", "sorafenib"],
    "esophageal cancer": ["cisplatin", "5-fluorouracil", "pembrolizumab"],
    "cervical cancer": ["cisplatin", "paclitaxel", "bevacizumab"],
    "leukemia": ["chemotherapy", "targeted therapy", "stem cell transplant"],
    "lymphoma": ["chemotherapy", "rituximab", "brentuximab vedotin"],
    "myeloma": ["chemotherapy", "lenalidomide", "bortezomib"],
    "anxiety disorders": ["selective serotonin reuptake inhibitors (SSRIs)", "serotonin-norepinephrine reuptake inhibitors (SNRIs)", "benzodiazepines"],
    "attention deficit hyperactivity disorder (ADHD)": ["methylphenidate", "amphetamine", "atomoxetine"],
    "bipolar disorder": ["lithium", "antipsychotics", "anticonvulsants"],
    "obsessive-compulsive disorder (OCD)": ["selective serotonin reuptake inhibitors (SSRIs)", "clomipramine", "exposure and response prevention therapy"],
    "panic disorder": ["selective serotonin reuptake inhibitors (SSRIs)", "benzodiazepines", "exposure therapy"],
    "post-traumatic stress disorder (PTSD)": ["selective serotonin reuptake inhibitors (SSRIs)", "serotonin-norepinephrine reuptake inhibitors (SNRIs)", "cognitive behavioral therapy (CBT)"],
    "schizophrenia": ["antipsychotics", "psychosocial interventions", "cognitive behavioral therapy for psychosis"],
    "insomnia": ["zolpidem", "eszopiclone", "doxepin"],
    "narcolepsy": ["modafinil", "methylphenidate", "sodium oxybate"],
    "restless legs syndrome (RLS)": ["ropinirole", "pramipexole", "gabapentin enacarbil"],
    "social anxiety disorder": ["selective serotonin reuptake inhibitors (SSRIs)", "serotonin-norepinephrine reuptake inhibitors (SNRIs)", "cognitive behavioral therapy (CBT)"],
    "borderline personality disorder": ["dialectical behavior therapy (DBT)", "selective serotonin reuptake inhibitors (SSRIs)", "antipsychotics"],
    "eating disorders": ["cognitive behavioral therapy (CBT)", "selective serotonin reuptake inhibitors (SSRIs)", "antipsychotics"],
    "substance use disorder": ["behavioral therapies", "medications for withdrawal symptoms", "medications for cravings"],
    "autism spectrum disorder (ASD)": ["applied behavior analysis (ABA)", "antipsychotics", "stimulants"],
    "major depressive disorder (MDD)": ["selective serotonin reuptake inhibitors (SSRIs)", "serotonin-norepinephrine reuptake inhibitors (SNRIs)", "tricyclic antidepressants"],
    "seasonal affective disorder (SAD)": ["light therapy", "selective serotonin reuptake inhibitors (SSRIs)", "bupropion"],
    "postpartum depression": ["selective serotonin reuptake inhibitors (SSRIs)", "serotonin-norepinephrine reuptake inhibitors (SNRIs)", "counseling"],
    "premenstrual dysphoric disorder (PMDD)": ["selective serotonin reuptake inhibitors (SSRIs)", "oral contraceptives", "cognitive behavioral therapy (CBT)"],
    "schizoaffective disorder": ["antipsychotics", "mood stabilizers", "antidepressants"],
    "fibromyalgia": ["pregabalin", "duloxetine", "milnacipran"],
    "chronic fatigue syndrome (CFS)": ["cognitive behavioral therapy (CBT)", "graded exercise therapy (GET)", "medications for symptom management"],
    "temporomandibular joint disorder (TMJ)": ["muscle relaxants", "nonsteroidal anti-inflammatory drugs (NSAIDs)", "tricyclic antidepressants"],
    "attention deficit disorder (ADD)": ["methylphenidate", "dextroamphetamine", "lisdexamfetamine"],
    "bulimia nervosa": ["selective serotonin reuptake inhibitors (SSRIs)", "cognitive behavioral therapy (CBT)", "antidepressants"],
    "bipolar I disorder": ["mood stabilizers", "antipsychotics", "antidepressants"],
    "bipolar II disorder": ["mood stabilizers", "antidepressants", "antipsychotics"],
    "social phobia": ["selective serotonin reuptake inhibitors (SSRIs)", "cognitive behavioral therapy (CBT)", "beta blockers"],
    "generalized anxiety disorder (GAD)": ["selective serotonin reuptake inhibitors (SSRIs)", "serotonin-norepinephrine reuptake inhibitors (SNRIs)", "benzodiazepines"],
    "specific phobia": ["exposure therapy", "cognitive behavioral therapy (CBT)", "medications for symptom relief"],
    "panic attack": ["benzodiazepines", "selective serotonin reuptake inhibitors (SSRIs)", "tricyclic antidepressants"],
    "agoraphobia": ["selective serotonin reuptake inhibitors (SSRIs)", "cognitive behavioral therapy (CBT)", "benzodiazepines"],
    "adjustment disorder": ["supportive therapy", "cognitive behavioral therapy (CBT)", "medications for symptom relief"],
    "oppositional defiant disorder (ODD)": ["parent training", "behavioral therapy", "psychoeducation"],
    "conduct disorder": ["cognitive behavioral therapy (CBT)", "multisystemic therapy", "residential treatment"],
    "intermittent explosive disorder (IED)": ["cognitive behavioral therapy (CBT)", "antidepressants", "mood stabilizers"],
    "anorexia nervosa": ["nutritional rehabilitation", "cognitive behavioral therapy (CBT)", "antidepressants"],
    "borderline intellectual functioning": ["education interventions", "adaptive skills training", "behavioral therapy"],
    "learning disorders": ["individualized education programs (IEPs)", "educational accommodations", "remedial education"],
    "stuttering": ["speech therapy", "cognitive behavioral therapy (CBT)", "medications for symptom relief"],
    "autism": ["applied behavior analysis (ABA)", "speech therapy", "occupational therapy"],
    "intellectual disability": ["special education services", "behavioral interventions", "adaptive skills training"],
    "tic disorders": ["habit reversal training", "antipsychotics", "stimulant medications"],
    "motor skills disorder": ["occupational therapy", "physical therapy", "speech therapy"],
    "expressive language disorder": ["speech therapy", "language interventions", "assistive communication devices"],
    "communication disorders": ["speech therapy", "language interventions", "augmentative and alternative communication (AAC)"],
    "attachment disorders": ["therapeutic interventions", "attachment-focused therapy", "parent-child interaction therapy"],
    "reactive attachment disorder (RAD)": ["therapeutic interventions", "attachment-focused therapy", "parent-child interaction therapy"],
    "disinhibited social engagement disorder": ["therapeutic interventions", "attachment-focused therapy", "parent-child interaction therapy"],
    "dissociative identity disorder (DID)": ["psychotherapy", "cognitive behavioral therapy (CBT)", "eye movement desensitization and reprocessing (EMDR)"],
    "dissociative amnesia": ["psychotherapy", "cognitive behavioral therapy (CBT)", "eye movement desensitization and reprocessing (EMDR)"],
    "depersonalization disorder": ["psychotherapy", "cognitive behavioral therapy (CBT)", "medications for symptom relief"],
    "derealization disorder": ["psychotherapy", "cognitive behavioral therapy (CBT)", "medications for symptom relief"],
    "gender dysphoria": ["gender-affirming hormone therapy", "gender-affirming surgery", "psychotherapy"],
    "transvestic disorder": ["psychotherapy", "cognitive behavioral therapy (CBT)", "medications for comorbid conditions"],
    "sexual masochism disorder": ["psychotherapy", "cognitive behavioral therapy (CBT)", "medications for comorbid conditions"],
    "sexual sadism disorder": ["psychotherapy", "cognitive behavioral therapy (CBT)", "medications for comorbid conditions"],
    "pedophilic disorder": ["psychotherapy", "cognitive behavioral therapy (CBT)", "medications for comorbid conditions"],
    "exhibitionistic disorder": ["psychotherapy", "cognitive behavioral therapy (CBT)", "medications for comorbid conditions"],
    "voyeuristic disorder": ["psychotherapy", "cognitive behavioral therapy (CBT)", "medications for comorbid conditions"],
    "frotteuristic disorder": ["psychotherapy", "cognitive behavioral therapy (CBT)", "medications for comorbid conditions"],
    "feather fetishism": ["psychotherapy", "cognitive behavioral therapy (CBT)", "medications for comorbid conditions"],
    "gender identity disorder (GID)": ["psychotherapy", "hormone therapy", "gender-affirming surgery"],
    "other specified paraphilic disorder": ["psychotherapy", "cognitive behavioral therapy (CBT)", "medications for comorbid conditions"],
    "unspecified paraphilic disorder": ["psychotherapy", "cognitive behavioral therapy (CBT)", "medications for comorbid conditions"],
    "antisocial personality disorder": ["psychotherapy", "cognitive behavioral therapy (CBT)", "medications for comorbid conditions"],
    "avoidant personality disorder": ["psychotherapy", "cognitive behavioral therapy (CBT)", "medications for comorbid conditions"],
    "borderline personality disorder": ["psychotherapy", "dialectical behavior therapy (DBT)", "medications for comorbid conditions"],
    "dependent personality disorder": ["psychotherapy", "cognitive behavioral therapy (CBT)", "medications for comorbid conditions"],
    "histrionic personality disorder": ["psychotherapy", "cognitive behavioral therapy (CBT)", "medications for comorbid conditions"],
    "narcissistic personality disorder": ["psychotherapy", "cognitive behavioral therapy (CBT)", "medications for comorbid conditions"],
    "obsessive-compulsive personality disorder": ["psychotherapy", "cognitive behavioral therapy (CBT)", "medications for comorbid conditions"],
    "paranoid personality disorder": ["psychotherapy", "cognitive behavioral therapy (CBT)", "medications for comorbid conditions"],
    "schizoid personality disorder": ["psychotherapy", "cognitive behavioral therapy (CBT)", "medications for comorbid conditions"],
    "schizotypal personality disorder": ["psychotherapy", "cognitive behavioral therapy (CBT)", "medications for comorbid conditions"],
    "schizoaffective disorder": ["psychotherapy", "antipsychotics", "mood stabilizers"],
    "impulse control disorders": ["psychotherapy", "cognitive behavioral therapy (CBT)", "medications for comorbid conditions"],
    "neurodevelopmental disorders": ["behavioral interventions", "psychoeducation", "medications for symptom management"],
    "personality disorders": ["psychotherapy", "dialectical behavior therapy (DBT)", "medications for comorbid conditions"],
    "substance-related disorders": ["detoxification", "rehabilitation programs", "medications for withdrawal symptoms"],
    "psychotic disorders": ["antipsychotic medications", "psychotherapy", "hospitalization"],
    "disruptive, impulse-control, and conduct disorders": ["psychotherapy", "cognitive behavioral therapy (CBT)", "behavioral interventions"],
    "dissociative disorders": ["psychotherapy", "cognitive behavioral therapy (CBT)", "medications for comorbid conditions"],
    "gender dysphoria": ["psychotherapy", "gender-affirming hormone therapy", "gender-affirming surgery"],
    "paraphilic disorders": ["psychotherapy", "cognitive behavioral therapy (CBT)", "medications for comorbid conditions"],
    "other mental disorders": ["psychotherapy", "cognitive behavioral therapy (CBT)", "medications for comorbid conditions"],
    "hepatitis e":["ondansetron","promethazine","paracetamol"],
}

def search_medicine(disease):
    if disease.lower() in medicine_database:
        return medicine_database[disease.lower()]
    else:
        return "No medicines found for the specified disease."

if __name__ == "__main__":
    disease = input("Enter the name of the disease: ")
    medicines = search_medicine(disease)
    print("Medicines for", disease.capitalize() + ":")
    if isinstance(medicines, list):
        for medicine in medicines:
            print("-", medicine)
    else:
        print(medicines)
